-- ==========================================
-- SCRIPT DE INICIALIZACIÓN: BARBERÍA IA
-- Descripción: Esquema de base de datos para plataforma SaaS
-- ==========================================

-- 1. TABLA DE NEGOCIOS (EMPRESAS)
CREATE TABLE negocios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  stripe_customer_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABLA DE PLANES
CREATE TABLE planes (
  id INT PRIMARY KEY,
  codigo TEXT UNIQUE NOT NULL, -- 'free', 'basic', 'premium'
  nombre TEXT NOT NULL,
  precio_mxn NUMERIC NOT NULL,
  limite_sucursales INT NOT NULL,
  limite_empleados_sucursal INT NOT NULL,
  descripcion TEXT,
  activo BOOLEAN DEFAULT TRUE
);

-- Insertar planes iniciales
INSERT INTO planes (id, codigo, nombre, precio_mxn, limite_sucursales, limite_empleados_sucursal, descripcion)
VALUES 
(1, 'free', 'Plan Gratuito', 0, 1, 2, 'Para barberos independientes'),
(2, 'basic', 'Plan Emprendedor', 219, 2, 4, 'Para negocios en crecimiento'),
(3, 'premium', 'Plan Imperio', 499, 6, 10, 'Control total multi-sucursal');

-- 3. SUSCRIPCIONES DE NEGOCIOS
CREATE TABLE negocio_suscripciones (
  negocio_id BIGINT REFERENCES negocios(id) ON DELETE CASCADE PRIMARY KEY,
  plan_id INT REFERENCES planes(id),
  estado TEXT CHECK (estado IN ('trial', 'active', 'past_due', 'canceled')),
  fecha_fin_periodo TIMESTAMPTZ,
  stripe_subscription_id TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SUCURSALES
CREATE TABLE sucursales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id BIGINT REFERENCES negocios(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  direccion TEXT,
  telefono TEXT,
  stripe_account_id TEXT, -- Para Stripe Connect
  onboarding_completo BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. PERFILES DE USUARIO (AUTH)
CREATE TABLE usuarios_perfiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  negocio_id BIGINT REFERENCES negocios(id),
  sucursal_id BIGINT REFERENCES sucursales(id), -- NULL si es el Dueño
  nombre_completo TEXT,
  email TEXT UNIQUE,
  rol TEXT CHECK (rol IN ('owner', 'branch', 'admin')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. EMPLEADOS
CREATE TABLE empleados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id BIGINT REFERENCES sucursales(id) ON DELETE CASCADE,
  negocio_id BIGINT REFERENCES negocios(id),
  nombre TEXT NOT NULL,
  especialidad TEXT,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. SERVICIOS
CREATE TABLE servicios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id BIGINT REFERENCES sucursales(id) ON DELETE CASCADE,
  negocio_id BIGINT REFERENCES negocios(id),
  nombre TEXT NOT NULL,
  precio_base NUMERIC NOT NULL,
  duracion_minutos INT NOT NULL,
  imagen_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. CITAS (EL CORAZÓN DEL SISTEMA)
CREATE TABLE citas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id BIGINT REFERENCES negocios(id),
  sucursal_id BIGINT REFERENCES sucursales(id),
  empleado_id BIGINT REFERENCES empleados(id),
  cliente_nombre TEXT NOT NULL,
  cliente_telefono TEXT,
  cliente_email TEXT,
  fecha_hora_inicio TIMESTAMPTZ NOT NULL,
  fecha_hora_fin TIMESTAMPTZ NOT NULL,
  estado TEXT DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'confirmada', 'cancelada', 'completada')),
  pagado BOOLEAN DEFAULT FALSE,
  monto_total NUMERIC,
  stripe_payment_id TEXT,
  tipo_reserva TEXT DEFAULT 'web' CHECK (tipo_reserva IN ('web', 'whatsapp', 'manual')),
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. SERVICIOS POR CITA (Relación N a N)
CREATE TABLE cita_servicios (
  cita_id BIGINT REFERENCES citas(id) ON DELETE CASCADE,
  servicio_id BIGINT REFERENCES servicios(id),
  precio_cobrado NUMERIC NOT NULL,
  PRIMARY KEY (cita_id, servicio_id)
);

-- ==========================================
-- SEGURIDAD: ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE negocios ENABLE ROW LEVEL SECURITY;
ALTER TABLE sucursales ENABLE ROW LEVEL SECURITY;
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;

-- Ejemplo de política: Solo los miembros del negocio pueden ver sus citas
CREATE POLICY "Acceso por negocio_id" ON citas
  FOR ALL
  USING (negocio_id IN (
    SELECT negocio_id FROM usuarios_perfiles WHERE id = auth.uid()
  ));
